destination: _site/
url: "http://127.0.0.1:4013"
baseurl: "/lambda-pdf"
port: 4011
output: pdf
product: lambda
print_title: Lambda
print_subtitle: version 0.1
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: lambda_sidebar
