destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/cs-pdf"
port: 4010
output: pdf
product: cs
print_title: The Celestial Stats Project
print_subtitle: version 0.1
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: cs_sidebar
